### ISSUE TITLE
remove reference to former lead developer of yuzu codebase in readme.md

### ISSUE THREAD

**Issue by borntohonk** [Nikilites/nuzu#2] opened 2024-03-05 11:24 UTC
https://github.com/Nikilites/nuzu/blob/main/README.md?plain=1#L59

This individual literally has had their lawyer negotiate them not being permitted to touch or support anything switch related again, including yuzu/nuzu or whatever you want to label it as.

keeping that reference might open your fork to problems (nintendo) more rapidly, and inadvertently cause the person you're naming legal trouble.

**Comment by 42yeah** [comment] 2024-03-05 13:42
The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.

**Comment by Nikilites** [comment] 2024-03-05 13:53
> The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.

I apologize for any confusion or concern caused by the current state of the project. I understand your worries about the legitimacy of the developer and their intentions. It's essential for us to address these issues transparently and ensure that the project operates ethically and responsibly. I'll take your concerns into account and work towards resolving any outstanding issues. Thank you for bringing this to my attention.

**Comment by 42yeah** [comment] 2024-03-05 13:55
> > The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.
> 
> I apologize for any confusion or concern caused by the current state of the project. I understand your worries about the legitimacy of the developer and their intentions. It's essential for us to address these issues transparently and ensure that the project operates ethically and responsibly. I'll take your concerns into account and work towards resolving any outstanding issues. Thank you for bringing this to my attention.

Uhhhh did you just replied to me using ChatGPT ????

**Comment by Minecon724** [comment] 2024-03-05 13:56
> > The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.
> 
> I apologize for any confusion or concern caused by the current state of the project. I understand your worries about the legitimacy of the developer and their intentions. It's essential for us to address these issues transparently and ensure that the project operates ethically and responsibly. I'll take your concerns into account and work towards resolving any outstanding issues. Thank you for bringing this to my attention.

this message shows all your intentions

**Comment by Nikilites** [comment] 2024-03-05 13:58
> > > The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.
> > 
> > 
> > I apologize for any confusion or concern caused by the current state of the project. I understand your worries about the legitimacy of the developer and their intentions. It's essential for us to address these issues transparently and ensure that the project operates ethically and responsibly. I'll take your concerns into account and work towards resolving any outstanding issues. Thank you for bringing this to my attention.
> 
> Uhhhh did you just replied to me using ChatGPT ????

No?? I don't use AI for conversation. Don't blame me for something I didn't do, maybe you are thinking that because my English isn't perfect since I'm Italian

**Comment by Nikilites** [comment] 2024-03-05 13:59
And please calm down because i can't do only this in my life.

**Comment by borntohonk** [comment] 2024-03-05 13:59
> So I hide that he is Yuzu's successor?

no shit? isn't it obvious?

You aren't hiding that they are the lead dev, but you left in the statement to SEEK SUPPORT FROM THEM.

**Comment by Minecon724** [comment] 2024-03-05 14:00
> > > > The current developer of this project is not legitimate and may be using this to only gain clout. I have raised concerns (#4) and they immediately closed them without addressing any of it.
> > > 
> > > 
> > > I apologize for any confusion or concern caused by the current state of the project. I understand your worries about the legitimacy of the developer and their intentions. It's essential for us to address these issues transparently and ensure that the project operates ethically and responsibly. I'll take your concerns into account and work towards resolving any outstanding issues. Thank you for bringing this to my attention.
> > 
> > 
> > Uhhhh did you just replied to me using ChatGPT ????
> 
> No?? I don't use AI for conversation. Don't blame me for something I didn't do, maybe you are thinking that because my English isn't perfect since I'm Italian

dude that text is not at all consistent with your writing style. why were you talking in 3rd person then

**Comment by Minecon724** [comment] 2024-03-05 14:01
> And please calm down because i can't do only this in my life.

that's right, you can do better

**Closed** 2024-03-05 14:05 UTC

**Comment by Haditah4shinji** [comment] 2024-03-05 14:53
If you or anyone working on this can legit make improvements to the build, then that's all that matters.
